### ISSUE TITLE
f

### ISSUE THREAD

**Issue by Yalzy** [Eritz/gbf_raid_bot#3]
f

**Comment by Yalzy** [comment]
Here's console code 

https://i.imgur.com/28wRuKM.png

**Comment by Yalzy** [comment]
my setting 
1 https://i.imgur.com/gL7rpp3.png
2 https://i.imgur.com/Aw0jY8l.png
3 https://i.imgur.com/EBNZvmA.png
4 https://i.imgur.com/AauZIHd.png
5 https://i.imgur.com/sKYrNaM.png
6 https://i.imgur.com/Ey16r53.png
7 https://i.imgur.com/TpUhNb8.png
8 https://i.imgur.com/9rlQ30f.png

anything wrong ?

**Comment by Eritz** [comment]
Hi, unfortunately I'm not too active with the game anymore, but I would suggest playing around with the timer in the bot file. Specifically, the `time.sleep()`

**Comment by Yalzy** [comment]
Hi change time.sleep() to 5 and still not work

anyway ty for answer
